name = "Repos"
uuid = "87f129d4-1535-4407-9638-d5031d1b8dee"

[deps]
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Diana = "070d9d8b-17a7-5814-83fa-42438ba5c6e0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
ConfParser = "0.1"
Diana = "0.2"
JSON3 = "0.1"
LibPQ = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Test", "Pkg"]
